enum DB_TUPLE
{
  DB_USER_ID,
  DB_SCURRY_ID,
  DB_COLOR,
  DB_SQUIRREL,
  DB_HIGH_ACORN_COUNT,
  DB_STOLEN_ACORNS,
  DB_ENCOUNTER,
  DB_TIMESTAMP,
  DB_MAIN_CD,
  DB_CONJURED_ACORNS,
  DB_SECTION,
  DB_PURCHASED,
  DB_TREASURY,
  DB_DAILY_PIES,
  DB_DAILY_DAY,

  DB_STORY_ID,
  DB_GL_STORY,
  DB_SP_STORY,
  DB_NE_STORY,
  DB_DG_STORY,
  DB_LA_STORY,

  DB_SIZE
};


enum GAME_TUPLE
{
  GAME_USER_ID,
  GAME_SCORE,
  GAME_PIECE_COUNT,
  GAME_HISTORY,
  GAME_PIE_ONE,
  GAME_PIE_TWO,
  GAME_PIE_THREE,
  GAME_CURRENT_PIECE,
  GAME_NEXT_PIECE,
  GAME_SIZE
};

// TODO: SCURRY RES
enum DB_SCURRY 
{
  DB_SCURRY_OWNER_ID,
  DB_SCURRY_NAME,
  DB_WAR_STASH,
  DB_WAR_FLAG,
  DB_PREV_STOLEN_ACORNS
};

enum SEASONS
{
  SEASON_SPRING,
  SEASON_SUMMER,
  SEASON_FALL,
  SEASON_WINTER,
  SEASON_SIZE
};

enum INVITE_RES {
  DB_INVITE_OWNER, // scurry owner
  DB_INVITE_USER, // inquiring user
  DB_INVITE_MSG, // message id of invite
  DB_INVITE_CHANNEL, // channel slash command was sent in
  DB_INVITE_TIME // time slash command was sent
};

enum SCURRY_RANKS 
{
  SEED_NOT,
  OAKFFICIAL,
  ROYAL_NUT,
  RANK_SIZE
};

enum SLICES 
{
  SLICE_TOP_LEFT,
  SLICE_TOP_CENTER,
  SLICE_TOP_RIGHT,
  SLICE_MID_RIGHT,
  SLICE_BOTTOM_RIGHT,
  SLICE_BOTTOM_CENTER,
  SLICE_BOTTOM_LEFT,
  SLICE_MID_LEFT,
  SLICES_SIZE
};

/* Help Page Indexes */
enum P_TOPIC {
  P_TOPIC_INTRO,
  P_TOPIC_PROGRESSION,
  P_TOPIC_STORY,
  P_TOPIC_SQUIRREL,
  P_TOPIC_CHANGE_COLOR,
  P_TOPIC_STEAL,
  P_TOPIC_SCURRY,
  P_TOPIC_DAILY,
  P_TOPIC_HELP,
  P_TOPIC_SIZE
};

enum E_TOPIC {
  E_TOPIC_ACORN_COUNT,
  E_TOPIC_SEASONS,
  E_TOPIC_SPRING,
  E_TOPIC_SUMMER,
  E_TOPIC_FALL,
  E_TOPIC_WINTER,
  E_TOPIC_CHRISTMAS,
  E_TOPIC_SIZE
};

enum S_TOPIC {
  S_TOPIC_UTILS,
  S_TOPIC_WARS,
  S_TOPIC_AFTERMATH,
  S_TOPIC_SIZE
};

enum SQ_TOPIC {
  SQ_TOPIC_TRADITIONAL,
  SQ_TOPIC_SPRING,
  SQ_TOPIC_SUMMER,
  SQ_TOPIC_FALL,
  SQ_TOPIC_WINTER,
  SQ_TOPIC_SIZE
};

enum STORY_TOPIC {
  STORY_GRASSLANDS,
  STORY_SEEPING_SANDS,
  STORY_NATURE_END,
  STORY_DEATH_GRIP,
  STORY_LAST_ACORN,
  STORY_TOPIC_SIZE
};

enum RULE_TOPICS {
  RULE_RESPECT,
  RULE_CONTENT,
  RULE_BOT,
  RULE_ADVERTISING,
  RULE_WARNING,
  RULE_SIZE
};